[package]
name = "linearalgebra"
version = "0.1.0"
authors = ["Debasish Ray Chawdhuri <debasish@geekyarticlesc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.2.6"
num-complex = "0.2.4"
